package com.example.tradejournal

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

/** زبان برنامه: فارسی (پیش‌فرض) یا انگلیسی */
object Lang {
    var en by mutableStateOf(false)

    fun load(c: Context) {
        en = c.getSharedPreferences("prefs", Context.MODE_PRIVATE).getString("lang", "fa") == "en"
    }

    fun set(c: Context, english: Boolean) {
        en = english
        c.getSharedPreferences("prefs", Context.MODE_PRIVATE).edit()
            .putString("lang", if (english) "en" else "fa").apply()
    }
}

/** ترجمه‌ی یک متن فارسی؛ در حالت فارسی همان متن برمی‌گردد */
fun tr(s: String): String = if (Lang.en) (EN[s] ?: s) else s

private val EN: Map<String, String> = mapOf(
    " از " to " of ",
    " روز زیان‌ده" to " losing days",
    " روز سودده، " to " winning days, ",
    " معامله رایگان رسیدی. (ارتقا به پرو در مرحله بعد اضافه می‌شود)" to " free trades. (Pro upgrade will be added in a later step)",
    "آبان" to "Aban",
    "آخرین معاملات" to "Recent trades",
    "آذر" to "Azar",
    "اثر انگشت (با پین پشتیبان)" to "Fingerprint (with backup PIN)",
    "اثر انگشت در دسترس نیست" to "Fingerprint is not available",
    "اثر انگشت را تایید کن" to "Confirm your fingerprint",
    "احساس تو و نتیجه معامله" to "Your mood vs. results",
    "احساست هنگام این معامله" to "How did you feel during this trade?",
    "اردیبهشت" to "Ordibehesht",
    "اسفند" to "Esfand",
    "الگو" to "Pattern",
    "امنیت" to "Security",
    "انصراف" to "Cancel",
    "انگشتت را روی سنسور بگذار (یا روی دایره بزن)" to "Place your finger on the sensor (or tap the circle)",
    "اگه فراموششون کنی راه بازیابی نیست و باید اطلاعات اپ از تنظیمات گوشی پاک بشه." to "If you forget them there is no recovery, and the app data must be cleared from the phone settings.",
    "این گوشی اثر انگشت ندارد؛ از پین پشتیبان استفاده کن" to "This phone has no fingerprint sensor; use the backup PIN",
    "با ثبت معامله‌ها، اینجا می‌بینی با کدوم احساس چقدر سود می‌کنی." to "Once you log trades, you will see here how much you make with each mood.",
    "باز کردن برنامه" to "Unlock the app",
    "بازار آرام" to "Quiet market",
    "بازار بسته است (آخر هفته)" to "Market closed (weekend)",
    "بازگشت" to "Back",
    "بدون قفل" to "No lock",
    "بدون یادداشت" to "No note",
    "برای تایید، دوباره وارد کن" to "Enter it again to confirm",
    "برنامه قفل است" to "The app is locked",
    "به سقف " to "You have reached the limit of ",
    "بهترین" to "Best",
    "بهمن" to "Bahman",
    "تایید اثر انگشت" to "Confirm fingerprint",
    "تریدر" to "Trader",
    "تقویم" to "Calendar",
    "تقویم سود و زیان" to "Profit & loss calendar",
    "تنظیمات" to "Settings",
    "توجه: پین و الگو فقط روی همین گوشی و به‌صورت رمزنگاری‌شده ذخیره می‌شن. " to "Note: your PIN and pattern are stored only on this phone, in hashed form. ",
    "توکیو" to "Tokyo",
    "تیر" to "Tir",
    "ثبت معامله" to "Log trade",
    "ج" to "Fr",
    "جمع این ماه" to "This month's total",
    "حالت نمایش" to "Theme",
    "حداقل ۴ نقطه را وصل کن" to "Connect at least 4 dots",
    "حذف" to "Delete",
    "خانه" to "Home",
    "خرداد" to "Khordad",
    "خرس" to "Bear",
    "خرس قطبی" to "Polar bear",
    "خرید" to "Buy",
    "خطا در اثر انگشت" to "Fingerprint error",
    "خلاصه عملکرد" to "Performance summary",
    "خودت انتخاب کن که ژورنالت با چه روشی قفل بشه." to "Choose how your journal gets locked.",
    "خودکار" to "Auto",
    "د" to "Mo",
    "دو بار یکسان نبود، دوباره امتحان کن" to "They did not match, try again",
    "دی" to "Dey",
    "ذخیره معامله" to "Save trade",
    "رمز اشتباه است" to "Wrong code",
    "رنگ اصلی" to "Accent color",
    "روز" to "Day",
    "زبان" to "Language",
    "زیان" to "Loss",
    "س" to "Tu",
    "سلام، " to "Hello, ",
    "سهم رایگان شما" to "Your free quota",
    "سود" to "Profit",
    "سود خالص" to "Net profit",
    "سیدنی" to "Sydney",
    "ش" to "Sa",
    "شب" to "Night",
    "شخصیت‌های احساسی" to "Mood characters",
    "شخصی‌سازی" to "Personalization",
    "شهریور" to "Shahrivar",
    "ظاهر" to "Appearance",
    "عادی" to "Calm",
    "عصبی" to "Angry",
    "عکس معامله" to "Trade photo",
    "فارسی" to "فارسی",
    "فروردین" to "Farvardin",
    "فروش" to "Sell",
    "قفل برنامه" to "App lock",
    "قیمت خروج" to "Exit price",
    "قیمت ورود" to "Entry price",
    "لندن" to "London",
    "لیست خالی است." to "The list is empty.",
    "مبلغ (دلار)" to "Amount (USD)",
    "مرداد" to "Mordad",
    "مضطرب" to "Anxious",
    "مطمئن" to "Confident",
    "معاملات" to "Trades",
    "مهر" to "Mehr",
    "نام شما" to "Your name",
    "نماد دیگر (مثلاً USDJPY)" to "Other symbol (e.g. USDJPY)",
    "نیویورک" to "New York",
    "همپوشانی" to "Overlap",
    "همین الان قفل کن و امتحان کن" to "Lock now and test it",
    "هنوز معامله‌ای ثبت نکردی. با دکمه + شروع کن." to "You haven't logged any trades yet. Tap + to start.",
    "ورود با اثر انگشت" to "Use fingerprint",
    "ورود با پین پشتیبان" to "Use backup PIN",
    "وین‌ریت" to "Win rate",
    "٪" to "%",
    "پ" to "Th",
    "پین ۴ رقمی" to "4-digit PIN",
    "پیوست" to "Attachments",
    "چ" to "We",
    "گاو" to "Cow",
    "گاو نر" to "Bull",
    "ی" to "Su",
    "یادداشت" to "Note",
    "یک الگو بکش" to "Draw a pattern",
    "یک پین پشتیبان بساز" to "Create a backup PIN",
    "یک پین ۴ رقمی بساز" to "Create a 4-digit PIN",
    "⏹ توقف ضبط" to "⏹ Stop recording",
    "🎙 ضبط دوباره" to "🎙 Record again",
    "🎙 ضبط ویس" to "🎙 Record voice",
    "📷 تغییر عکس" to "📷 Change photo",
    "📷 عکس چارت" to "📷 Chart photo"
)
